version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Customer360"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-196afdw3nlm3n"
s3_prefix = "Customer360"
region = "eu-west-2"
profile = "eagle"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
